---

- name: Define php_opcache_conf_filename.
  set_fact:
    php_opcache_conf_filename="{{ __php_opcache_conf_filename }}"
  when: php_opcache_conf_filename is not defined

- name: Define php_extension_conf_paths.
  set_fact:
    php_extension_conf_paths="{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined

- name: Install PHP Base Package
  yum:
    name="{{ php_prefix }}"
    state="{{ php_package_state }}"

- name: Install PHP
  yum:
    name="{{ php_prefix }}-{{ item }}"
    state="{{ php_package_state }}"
  with_items: "{{ php_base_packages + php_extra_base_packages }}"

- name: Install PECL Mods
  yum:
    name="{{ php_prefix }}-{{ item }}"
    state="{{ php_package_state }}"
  with_items: "{{ php_pecl_modules + php_extra_pecl_modules }}"

- name: Install Browscap.INI
  template:
    src="browscap.ini.j2"
    dest="/etc/browscap.ini"
    owner="root"
    group="root"
    mode="0644"
  when: php_install_browscap_ini

- name: Gather SCL Binary List
  find:
    paths="{{ php_root }}/usr/bin"
    recurse="no"
  register: found

- name: Symlink SCL Binaries
  file:
    src="{{ item.path }}"
    dest="/usr/bin/{{ item.path | basename }}"
    owner="root"
    group="root"
    mode="0755"
    state="link"
    force="{{ item.isreg }}"
  with_items: "{{ found.files }}"
  when: 
    - php_symlink_scl_bins
    - item.isreg

- name: Symlink PHP.ini
  file:
    src="{{ php_config_root }}/php.ini"
    dest="/etc/php.ini"
    owner="root"
    group="root"
    mode="0644"
    state="link"
    force=true
  when: php_single_version

- name: Tweak PHP.ini Vars
  ini_file:
    path="{{ php_config_root }}/php.ini"
    section="PHP"
    option="{{ item.name }}"
    value="{{ item.value }}"
    backup="no"
    create="no"
  with_items: "{{ php_ini_config }}"

- name: Setup FPM
  include: "fpm.yml"
  when: php_fpm_enabled
  static: no

- name: Setup Opcache
  include: "opcache.yml"
  static: no
